# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d78b504a0125836e87ba601b29683a9fa29f131decb691b003f170ba3cb373850c8260c5128353d394a3da6f054fbde237d7d6b94c0935010bf6f4ab2d8bfe0

test:
  secret_key_base: 1e4b57ef39e762a84d30ab524ffcf3542b79372e4c6c36a853a1e4ea0ab737c937e3a7ca05963d820cada22226b693bb3bd70f63d096b5b9b85d7776eedbc208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
